spring:
  application:
    name: ai-code-mother-name
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_mother
    username: root
    password: 1234

server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wyb.aicodemotherback.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-a605949e13ac46049f3fc0167f4f8153
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      timeout: 300s  # 设置超时时间为5分钟
      max-retries: 3  # 最大重试次数
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-a605949e13ac46049f3fc0167f4f8153
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

